let name = 'nardo'

// try {
//     name.map((item, i) => {
//         return item.name
//     })
// }catch(e) {
//     console.log(e)
//     Exception.error(e)
// }

let error500 = new Promise((resolve, reject) => {
    return reject(500)
})
// name.map((item, i) => {
//     return item.name
// })

